name: 'Check for Updates'
description: 'Check for software updates using endoflife.date and create issues for new releases'
author: 'lbussell'

inputs:
  product:
    description: 'The endoflife.date product ID (e.g., ubuntu, alpine-linux)'
    required: true
  token:
    description: 'GitHub token for creating issues. Requires issues: write permissions.'
    required: false
    default: ${{ github.token }}

runs:
  using: 'composite'
  steps:
    - name: Restore cached version
      id: cache-restore
      uses: actions/cache/restore@v5.0.1
      with:
        path: .endoflife-cache
        key: endoflife-${{ inputs.product }}

    - name: Check for updates
      uses: actions/github-script@v8.0.0
      env:
        PRODUCT: ${{ inputs.product }}
      with:
        github-token: ${{ inputs.token }}
        script: |
          const fs = require('fs');
          const path = require('path');
          const product = process.env.PRODUCT;

          // Fetch latest release from endoflife.date API
          core.info(`Checking for updates to ${product}...`);

          const response = await fetch(`https://endoflife.date/api/${product}.json`);
          if (!response.ok) {
            throw new Error(`Failed to fetch data for ${product}: ${response.statusText}`);
          }

          const releases = await response.json();
          if (!releases || releases.length === 0) {
            throw new Error(`No releases found for ${product}`);
          }

          // Get the latest release
          const latestRelease = releases[0];
          const latestVersion = latestRelease.cycle || latestRelease.latest;
          const releaseDate = latestRelease.releaseDate || latestRelease.release || 'Unknown';
          const eolDate = latestRelease.eol || 'Unknown';
          const lts = latestRelease.lts || false;

          core.info(`Latest version: ${latestVersion}`);
          core.info(`Release date: ${releaseDate}`);

          // Read cached version
          const cacheDir = '.endoflife-cache';
          const cacheFile = path.join(cacheDir, `${product}.txt`);
          let cachedVersion = null;

          if (fs.existsSync(cacheFile)) {
            cachedVersion = fs.readFileSync(cacheFile, 'utf8').trim();
            core.info(`Cached version: ${cachedVersion}`);
          } else {
            core.info('No cached version found');
          }

          // Check if there's a new release
          if (cachedVersion !== latestVersion) {
            core.info(`New release detected: ${latestVersion}`);

            // Create issue
            const issueTitle = `New ${product} release: ${latestVersion}`;
            const issueBody = `A new version of **${product}** is available!\n\n` +
              `- **Version**: ${latestVersion}\n` +
              `- **Release Date**: ${releaseDate}\n` +
              `- **End of Life**: ${eolDate}\n` +
              `- **LTS**: ${lts}\n\n` +
              `Previous version: ${cachedVersion || 'None'}\n\n` +
              `For more information, visit: https://endoflife.date/${product}`;

            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
              labels: ['dependencies', 'update-available']
            });

            core.info(`Created issue #${issue.data.number}`);

            // Update cache file
            if (!fs.existsSync(cacheDir)) {
              fs.mkdirSync(cacheDir, { recursive: true });
            }
            fs.writeFileSync(cacheFile, latestVersion);
            core.info(`Updated cache with version: ${latestVersion}`);

            core.setOutput('new-version', latestVersion);
            core.setOutput('issue-number', issue.data.number);
          } else {
            core.info('No new release detected');
            core.setOutput('new-version', '');
            core.setOutput('issue-number', '');
          }

    - name: Save cached version
      uses: actions/cache/save@v5.0.1
      if: always()
      with:
        path: .endoflife-cache
        key: endoflife-${{ inputs.product }}

outputs:
  new-version:
    description: 'The new version if one was found, empty string otherwise'
    value: ${{ steps.check-for-updates.outputs.new-version }}
  issue-number:
    description: 'The issue number created if a new version was found, empty string otherwise'
    value: ${{ steps.check-for-updates.outputs.issue-number }}

branding:
  icon: 'alert-circle'
  color: 'blue'
